function Inventory() { const { user } = useAuth(); const [products, setProducts] = useState(null); const [error, setError] = useState(''); const load = () => productApi.getFarmerProducts(user.id).then(setProducts).catch((e) => setError(apiError(e))); useEffect(load, [user.id]); const adjust = async (id, direction) => { try { await productApi.adjustStock(id, 1, direction); load() } catch (e) { setError(apiError(e)) } }; return <section className="section narrow"><div className="eyebrow">Stock control</div><h1>Keep the shelves full.</h1><ErrorBox message={error} />{products === null ? <Loading label="Loading inventory..." /> : products.length ? <div className="seller-table">{products.map((product) => <div className="seller-product" key={product.id}><div><h3>{product.name}</h3><p>{product.location} · {product.unit}</p></div><span className={`status status-${product.status.toLowerCase()}`}>{product.quantityAvailable} available</span><div className="table-actions"><button className="stock-button" onClick={() => adjust(product.id, 'decrease')}>- 1</button><button className="stock-button" onClick={() => adjust(product.id, 'increase')}>+ 1</button></div></div>)}</div> : <Empty title="You have no inventory yet." action="Add your first listing" to="/seller/products/new" />}</section> }
import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import Layout from './components/Layout'
import Loading from './components/Loading'
import ProductCard from './components/ProductCard'
import ProtectedRoute from './components/ProtectedRoute'
import { useAuth } from './context/AuthContext'
import { useCart } from './context/CartContext'
import { apiError } from './api/apiClient'
import { authApi } from './api/authApi'
import { marketApi } from './api/marketApi'
import { productApi } from './api/productApi'
import { productImage } from './utils/productMedia'

const categories = ['Vegetables', 'Fruits', 'Cereals', 'Legumes', 'Dairy', 'Poultry', 'Root crops']
const money = (value) => `KSh ${Number(value || 0).toLocaleString()}`
const date = (value) => value ? new Date(value).toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'
function ErrorBox({ message }) { return message ? <div className="error-box">{message}</div> : null }
function Empty({ title, action, to = '/products' }) { return <div className="empty-state"><span className="empty-mark">+</span><h3>{title}</h3>{action && <Link className="button" to={to}>{action}</Link>}</div> }

function Home() {
  const [featured, setFeatured] = useState([]); const [loading, setLoading] = useState(true)
  useEffect(() => { productApi.getProducts({ status: 'AVAILABLE', limit: 4 }).then(({ data }) => setFeatured(data || [])).catch(() => {}).finally(() => setLoading(false)) }, [])
  return <>
    <section className="hero"><div className="hero-copy"><div className="eyebrow">The local harvest, delivered</div><h1>Food tastes better when you know where it grew.</h1><p>Meet the farmers behind your food. Shop fresh produce with transparent prices, fairer trade, and less distance between field and fork.</p><div className="hero-actions"><Link className="button button-large" to="/products">Browse the market <span>→</span></Link><Link className="button button-outline button-large" to="/register/seller">Sell your harvest</Link></div><div className="hero-proof"><span><b>01</b> Direct from growers</span><span><b>02</b> Seasonal and fresh</span></div></div><div className="hero-art"><div className="art-label">TODAY'S<br /><strong>HARVEST</strong></div><div className="sun" /><div className="field field-one" /><div className="field field-two" /><div className="field field-three" /><div className="plant plant-one">╱╲<br />╱╲</div><div className="plant plant-two">╱╲<br />╱╲</div></div></section>
    <section className="section categories-section" id="categories"><div className="section-heading"><div><div className="eyebrow">Explore the harvest</div><h2>What are you cooking?</h2></div><Link className="text-link" to="/products">View all produce →</Link></div><div className="category-grid">{categories.map((category, index) => <Link to={`/products?category=${category}`} className={`category category-${index + 1}`} key={category}><span>0{index + 1}</span><strong>{category}</strong><em>→</em></Link>)}</div></section>
    <section className="section featured-section"><div className="section-heading"><div><div className="eyebrow">From this week's harvest</div><h2>Fresh picks</h2></div><p>Small farms, big flavour.</p></div>{loading ? <Loading label="Finding fresh picks..." /> : featured.length ? <div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <Empty title="The market is being stocked." action="Browse the market" />}</section>
    <section className="callout"><div><div className="eyebrow">For farmers and producers</div><h2>Your harvest deserves a closer market.</h2><p>Put your produce in front of people who care where their food comes from.</p></div><Link className="button button-light" to="/register/seller">Start selling →</Link></section>
  </>
}

function Products() {
  const [params, setParams] = useSearchParams(); const [products, setProducts] = useState([]); const [pagination, setPagination] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const query = Object.fromEntries(params.entries())
  const load = () => { setLoading(true); setError(''); productApi.getProducts({ status: query.status || 'AVAILABLE', ...query, page: query.page || 1, limit: 100 }).then((result) => { setProducts(result.data || []); setPagination(result.pagination || {}) }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }
  useEffect(load, [params.toString()])
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const next = Object.fromEntries([...data.entries()].filter(([, value]) => value)); setParams(next) }
  return <section className="section market-page"><div className="page-intro"><div><div className="eyebrow">The FarmMarket</div><h1>Good food, from good soil.</h1><p>Browse what local farms are harvesting right now.</p></div><div className="market-count">{pagination.total || 0}<span>listings</span></div></div><form className="filter-bar" onSubmit={submit}><input name="search" defaultValue={query.search} placeholder="Search tomatoes, farms, places..." /><select name="category" defaultValue={query.category || ''}><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select name="status" defaultValue={query.status || 'AVAILABLE'}><option value="AVAILABLE">In stock</option><option value="">All availability</option></select><select name="sortBy" defaultValue={query.sortBy || 'createdAt'}><option value="createdAt">Newest first</option><option value="price">Price</option></select><button className="button" type="submit">Search market</button></form><ErrorBox message={error} />{loading ? <Loading label="Loading produce..." /> : products.length ? <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <Empty title="No produce matches those filters." action="Reset the market" to="/products" />}{pagination.totalPages > 1 && <div className="pagination"><button disabled={(pagination.page || 1) <= 1} onClick={() => setParams({ ...query, page: (pagination.page || 1) - 1 })}>← Previous</button><span>Page {pagination.page} of {pagination.totalPages}</span><button disabled={pagination.page >= pagination.totalPages} onClick={() => setParams({ ...query, page: (pagination.page || 1) + 1 })}>Next →</button></div>}</section>
}

function ProductDetails() { const { id } = useParams(); const { addItem } = useCart(); const [product, setProduct] = useState(null); const [quantity, setQuantity] = useState(1); const [error, setError] = useState(''); useEffect(() => { productApi.getProduct(id).then(setProduct).catch((e) => setError(apiError(e))) }, [id]); if (error) return <section className="section"><ErrorBox message={error} /></section>; if (!product) return <Loading label="Loading product..." />; const available = product.status === 'AVAILABLE' && product.quantityAvailable > 0; return <section className="section detail-page"><Link className="back-link" to="/products">← Back to the market</Link><div className="detail-layout"><div className="detail-image" style={{ backgroundImage: `url(${productImage(product)})` }}><span>{product.location}</span></div><div className="detail-copy"><div className="eyebrow">{product.categoryName || 'Farm produce'} · {product.location}</div><h1>{product.name}</h1><p className="detail-description">{product.description || 'Fresh produce from a local farm, harvested with care.'}</p><div className="detail-price">{money(product.price)} <span>/ {product.unit}</span></div><div className="detail-facts"><span><b>Available stock</b>{product.quantityAvailable} {product.unit}s</span><span><b>Farmer</b>{product.farmerName || 'Local grower'}</span><span><b>Quality</b>Freshly harvested</span></div><div className="buy-row"><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button><span>{quantity}</span><button onClick={() => setQuantity(Math.min(product.quantityAvailable, quantity + 1))}>+</button></div><button className="button button-large" disabled={!available} onClick={() => addItem(product, quantity)}>{available ? 'Add to cart' : 'Out of stock'}</button></div></div></div></section> }

function Cart() { const { items, updateQuantity, removeItem, subtotal } = useCart(); if (!items.length) return <section className="section narrow"><div className="eyebrow">Your basket</div><h1>A little empty here.</h1><Empty title="Your cart is empty." action="Explore the market" /></section>; return <section className="section narrow"><div className="eyebrow">Your basket</div><h1>Ready when you are.</h1><div className="cart-layout"><div className="cart-list">{items.map(({ product, quantity }) => <div className="cart-item" key={product.id}><div className="cart-thumb" style={{ backgroundImage: product.imageUrl ? `url(${product.imageUrl})` : undefined }} /><div className="cart-item-copy"><h3>{product.name}</h3><p>{money(product.price)} / {product.unit}</p><div className="quantity"><button onClick={() => updateQuantity(product.id, quantity - 1)}>−</button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)}>+</button></div></div><strong>{money(product.price * quantity)}</strong><button className="remove" onClick={() => removeItem(product.id)}>Remove</button></div>)}</div><aside className="summary"><div className="eyebrow">Order summary</div><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Delivery</span><span>Calculated at checkout</span></div><hr /><div className="summary-total"><span>Total</span><strong>{money(subtotal)}</strong></div><Link className="button button-full" to="/checkout">Continue to checkout →</Link></aside></div></section> }

function Checkout() { const { items, subtotal, removeItem } = useCart(); const { user } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); if (!items.length) return <Navigate to="/cart" replace />; const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const data = new FormData(event.currentTarget); try { await marketApi.createOrder({ buyerId: user.id, deliveryLocation: data.get('deliveryLocation'), items: items.map(({ product, quantity }) => ({ productId: product.id, quantity })) }); items.forEach(({ product }) => removeItem(product.id)); navigate('/buyer/orders') } catch (e) { setError(apiError(e)) } finally { setSaving(false) } }; return <section className="section narrow"><div className="eyebrow">Almost there</div><h1>Where should we bring it?</h1><div className="checkout-layout"><form className="form-panel" onSubmit={submit}><label>Delivery location<input name="deliveryLocation" defaultValue={user?.location || ''} placeholder="Neighbourhood, town, or landmark" required minLength="2" /></label><ErrorBox message={error} /><button className="button button-full" disabled={saving}>{saving ? 'Placing order...' : 'Place order'}</button><p className="form-note">Your farmer confirms the final availability and our backend calculates the order total.</p></form><aside className="summary"><div className="eyebrow">Your order</div>{items.map(({ product, quantity }) => <div className="summary-line" key={product.id}><span>{product.name} × {quantity}</span><strong>{money(product.price * quantity)}</strong></div>)}<hr /><div className="summary-total"><span>Total</span><strong>{money(subtotal)}</strong></div></aside></div></section> }

function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const data = new FormData(event.currentTarget); try { const user = await login({ email: data.get('email'), password: data.get('password'), role: data.get('role') }); navigate((user.role || user.userType)?.toLowerCase() === 'seller' || (user.role || user.userType)?.toLowerCase() === 'farmer' ? '/seller' : '/buyer') } catch (e) { setError(apiError(e)) } finally { setSaving(false) } }; return <section className="auth-page"><div className="auth-art"><div className="eyebrow">Welcome back</div><h1>The market is waiting.</h1><p>Pick up where you left off, whether you are buying dinner or growing tomorrow's.</p></div><form className="auth-card" onSubmit={submit}><div className="eyebrow">Sign in</div><h2>Good to see you.</h2><label>I'm joining as<select name="role" defaultValue="buyer"><option value="buyer">A buyer</option><option value="seller">A farmer / seller</option></select></label><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required minLength="8" /></label><ErrorBox message={error} /><button className="button button-full" disabled={saving}>{saving ? 'Signing in...' : 'Sign in'}</button><p className="auth-switch">New here? <Link to="/register/buyer">Create a buyer account</Link> or <Link to="/register/seller">list your farm</Link>.</p></form></section> }

function Register({ seller = false }) { const navigate = useNavigate(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (data.password !== data.confirmPassword) return setError('Passwords do not match.'); if (data.password.length < 8) return setError('Use at least 8 characters for your password.'); setSaving(true); setError(''); try { const result = seller ? await authApi.registerSeller({ name: data.name, email: data.email, phone: data.phone, password: data.password, farmName: data.farmName, location: data.location, description: data.description }) : await authApi.registerBuyer({ name: data.name, email: data.email, phone: data.phone, password: data.password, location: data.location }); if (result?.accessToken || result?.token) navigate(seller ? '/seller' : '/buyer'); else navigate('/login') } catch (e) { setError(apiError(e)) } finally { setSaving(false) } }; return <section className="auth-page"><div className="auth-art"><div className="eyebrow">{seller ? 'For the people who grow it' : 'For the people who love it'}</div><h1>{seller ? 'Put your farm on the map.' : 'Make your table more local.'}</h1><p>{seller ? 'A simple, direct storefront for the harvest you are proud of.' : 'Meet local growers and get better produce without the guesswork.'}</p></div><form className="auth-card" onSubmit={submit}><div className="eyebrow">{seller ? 'Seller registration' : 'Buyer registration'}</div><h2>Create your account.</h2><label>Full name<input name="name" required minLength="2" /></label><label>Email<input name="email" type="email" required /></label><label>Phone number<input name="phone" required minLength="7" /></label><label>Location<input name="location" required minLength="2" placeholder="Town or county" /></label>{seller && <><label>Farm name<input name="farmName" required minLength="2" /></label><label>Farm story<textarea name="description" rows="3" placeholder="What do you grow?"></textarea></label></>}<label>Password<input name="password" type="password" required minLength="8" /></label><label>Confirm password<input name="confirmPassword" type="password" required minLength="8" /></label><ErrorBox message={error} /><button className="button button-full" disabled={saving}>{saving ? 'Creating account...' : `Create ${seller ? 'seller' : 'buyer'} account`}</button><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></form></section> }

function BuyerDashboard() { const { user } = useAuth(); const [orders, setOrders] = useState([]); useEffect(() => { marketApi.getBuyerOrders(user.id).then(setOrders).catch(() => {}) }, [user.id]); const pending = orders.filter((o) => !['COMPLETED', 'CANCELLED'].includes(o.status)).length; return <section className="section dashboard"><div className="page-intro"><div><div className="eyebrow">Buyer dashboard</div><h1>Good morning, {user.name?.split(' ')[0] || 'there'}.</h1><p>Your next good meal starts here.</p></div><Link className="button" to="/products">Shop the market →</Link></div><div className="stats"><div><span>Total orders</span><strong>{orders.length}</strong></div><div><span>In progress</span><strong>{pending}</strong></div><div><span>Member since</span><strong>{date(user.createdAt)}</strong></div></div><div className="section-heading"><h2>Recent orders</h2><Link className="text-link" to="/buyer/orders">View all →</Link></div>{orders.length ? <OrderList orders={orders.slice(0, 3)} /> : <Empty title="No orders yet." action="Find something fresh" />}</section> }
function OrderList({ orders, seller = false, onStatus }) { return <div className="order-list">{orders.map((order) => <article className="order-row" key={order.id}><div><div className="eyebrow">Order #{order.id.slice(0, 8)}</div><h3>{order.items?.length || 0} item{order.items?.length === 1 ? '' : 's'} · {date(order.createdAt)}</h3><p>{order.items?.map((item) => `${item.productName || `Product ${item.productId.slice(0, 6)}`} × ${item.quantity}`).join(', ') || 'Order items'} · {order.deliveryLocation}</p></div><div className="order-right"><span className={`status status-${order.status.toLowerCase()}`}>{order.status}</span><strong>{money(order.totalAmount)}</strong>{seller && <select value={order.status} onChange={(e) => onStatus(order.id, e.target.value)}><option>PENDING</option><option>CONFIRMED</option><option>PROCESSING</option><option>READY</option><option>COMPLETED</option><option>CANCELLED</option></select>}</div></article>)}</div> }
function BuyerOrders() { const { user } = useAuth(); const [orders, setOrders] = useState(null); useEffect(() => { marketApi.getBuyerOrders(user.id).then(setOrders).catch(() => setOrders([])) }, [user.id]); return <section className="section narrow"><div className="eyebrow">Your orders</div><h1>Everything you have coming.</h1>{orders === null ? <Loading label="Loading orders..." /> : orders.length ? <OrderList orders={orders} /> : <Empty title="No orders yet." action="Browse produce" />}</section> }
function Profile({ seller = false }) { const { user } = useAuth(); const [saved, setSaved] = useState(false); const [error, setError] = useState(''); const submit = async (event) => { event.preventDefault(); setError(''); const data = Object.fromEntries(new FormData(event.currentTarget)); try { seller ? await marketApi.updateFarmer(user.id, data) : await marketApi.updateBuyer(user.id, data); setSaved(true); setTimeout(() => setSaved(false), 2400) } catch (e) { setError(apiError(e)) } }; return <section className="section narrow"><div className="eyebrow">Your details</div><h1>Profile</h1><form className="form-panel profile-form" onSubmit={submit}><label>Full name<input name="name" defaultValue={user.name} required /></label><label>Email<input name="email" type="email" defaultValue={user.email} required /></label><label>Phone<input name="phone" defaultValue={user.phone} required /></label><label>Location<input name="location" defaultValue={user.location} required /></label>{seller && <><label>Farm name<input name="farmName" defaultValue={user.farmName} required /></label><label>Farm story<textarea name="description" defaultValue={user.description} rows="4" /></label></>}<ErrorBox message={error} />{saved && <div className="success-box">Profile updated successfully.</div>}<button className="button">Save changes</button></form></section> }
function SellerDashboard() { const { user } = useAuth(); const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); useEffect(() => { productApi.getFarmerProducts(user.id).then(setProducts).catch(() => {}); marketApi.getFarmerOrders(user.id).then(setOrders).catch(() => {}) }, [user.id]); return <section className="section dashboard"><div className="page-intro"><div><div className="eyebrow">Seller dashboard</div><h1>Welcome back, {user.name?.split(' ')[0] || 'farmer'}.</h1><p>Here is how your harvest is moving today.</p></div><Link className="button" to="/seller/products/new">Add produce →</Link></div><div className="stats"><div><span>Total listings</span><strong>{products.length}</strong></div><div><span>Available now</span><strong>{products.filter((p) => p.status === 'AVAILABLE').length}</strong></div><div><span>Orders to fulfil</span><strong>{orders.filter((o) => o.status === 'PENDING').length}</strong></div></div><div className="section-heading"><h2>Latest orders</h2><Link className="text-link" to="/seller/orders">Manage orders →</Link></div>{orders.length ? <OrderList orders={orders.slice(0, 4)} seller={() => {}} /> : <Empty title="No orders have arrived yet." action="Review your listings" to="/seller/products" />}</section> }
function SellerProducts() { const { user } = useAuth(); const [products, setProducts] = useState(null); const [error, setError] = useState(''); const load = () => productApi.getFarmerProducts(user.id).then(setProducts).catch((e) => setError(apiError(e))); useEffect(load, [user.id]); const remove = async (id) => { if (!window.confirm('Remove this listing from the market?')) return; try { await productApi.deleteProduct(id); load() } catch (e) { setError(apiError(e)) } }; return <section className="section"><div className="page-intro"><div><div className="eyebrow">Your storefront</div><h1>My produce.</h1></div><Link className="button" to="/seller/products/new">+ Add listing</Link></div><ErrorBox message={error} />{products === null ? <Loading label="Loading your listings..." /> : products.length ? <div className="seller-table">{products.map((p) => <div className="seller-product" key={p.id}><div className="product-mini-image" style={{ backgroundImage: p.imageUrl ? `url(${p.imageUrl})` : undefined }} /><div><h3>{p.name}</h3><p>{p.location} · {money(p.price)} / {p.unit}</p></div><span className={`status status-${p.status.toLowerCase()}`}>{p.quantityAvailable} in stock</span><div className="table-actions"><Link className="text-link" to={`/seller/products/${p.id}/edit`}>Edit</Link><button className="remove" onClick={() => remove(p.id)}>Delete</button></div></div>)}</div> : <Empty title="You haven't listed any produce yet." action="Add your first listing" to="/seller/products/new" />}</section> }
function ProductForm({ edit = false }) { const { id } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [categoriesList, setCategoriesList] = useState([]); const [initial, setInitial] = useState({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); useEffect(() => { marketApi.getCategories().then(setCategoriesList).catch(() => {}); if (edit) productApi.getProduct(id).then(setInitial).catch((e) => setError(apiError(e))) }, [edit, id]); const submit = async (event) => { event.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(event.currentTarget)); const payload = { ...data, farmerId: user.id, categoryId: data.categoryId, price: Number(data.price), quantityAvailable: Number(data.quantityAvailable), status: data.status || 'AVAILABLE' }; try { edit ? await productApi.updateProduct(id, payload) : await productApi.createProduct(payload); navigate('/seller/products') } catch (e) { setError(apiError(e)) } finally { setSaving(false) } }; return <section className="section narrow"><Link className="back-link" to="/seller/products">← Back to listings</Link><div className="eyebrow">{edit ? 'Edit listing' : 'New listing'}</div><h1>{edit ? 'Keep your listing current.' : 'What did you grow?'}</h1><form className="form-panel profile-form" onSubmit={submit}><label>Product name<input name="name" defaultValue={initial.name || ''} required minLength="2" /></label><label>Category<select name="categoryId" defaultValue={initial.categoryId || ''} required><option value="">Choose a category</option>{categoriesList.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Description<textarea name="description" defaultValue={initial.description || ''} rows="4" /></label><div className="form-grid"><label>Price<input name="price" type="number" min="0" step="0.01" defaultValue={initial.price || ''} required /></label><label>Unit<input name="unit" defaultValue={initial.unit || 'kg'} required /></label><label>Quantity available<input name="quantityAvailable" type="number" min="0" defaultValue={initial.quantityAvailable || 0} required /></label><label>Location<input name="location" defaultValue={initial.location || user.location || ''} required /></label></div><label>Image URL<input name="imageUrl" type="url" defaultValue={initial.imageUrl || ''} placeholder="https://..." /></label>{edit && <label>Status<select name="status" defaultValue={initial.status || 'AVAILABLE'}><option>AVAILABLE</option><option>OUT_OF_STOCK</option><option>INACTIVE</option></select></label>}<ErrorBox message={error} /><button className="button button-full" disabled={saving}>{saving ? 'Saving listing...' : edit ? 'Save listing' : 'Publish listing'}</button></form></section> }
function SellerOrders() { const { user } = useAuth(); const [orders, setOrders] = useState(null); const [error, setError] = useState(''); useEffect(() => { marketApi.getFarmerOrders(user.id).then(setOrders).catch((e) => { setError(apiError(e)); setOrders([]) }) }, [user.id]); const update = async (id, status) => { try { const updated = await marketApi.updateOrderStatus(id, status); setOrders((list) => list.map((order) => order.id === id ? updated : order)) } catch (e) { setError(apiError(e)) } }; return <section className="section narrow"><div className="eyebrow">Fulfilment</div><h1>Orders to send out.</h1><ErrorBox message={error} />{orders === null ? <Loading label="Loading seller orders..." /> : orders.length ? <OrderList orders={orders} seller onStatus={update} /> : <Empty title="No orders have arrived yet." action="Review your listings" to="/seller/products" />}</section> }

export default function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/products/:id" element={<ProductDetails />} /><Route path="/cart" element={<Cart />} /><Route path="/checkout" element={<ProtectedRoute role="buyer" />}><Route index element={<Checkout />} /></Route><Route path="/login" element={<Login />} /><Route path="/register/buyer" element={<Register />} /><Route path="/register/seller" element={<Register seller />} /><Route element={<ProtectedRoute />}><Route path="/produce-list" element={<Products />} /></Route><Route element={<ProtectedRoute role="buyer" />}><Route path="/buyer" element={<BuyerDashboard />} /><Route path="/buyer/orders" element={<BuyerOrders />} /><Route path="/buyer/profile" element={<Profile />} /></Route><Route element={<ProtectedRoute role="seller" />}><Route path="/seller" element={<SellerDashboard />} /><Route path="/seller/products" element={<SellerProducts />} /><Route path="/seller/inventory" element={<Inventory />} /><Route path="/seller/products/new" element={<ProductForm />} /><Route path="/seller/products/:id/edit" element={<ProductForm edit />} /><Route path="/seller/orders" element={<SellerOrders />} /><Route path="/seller/profile" element={<Profile seller />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout> }
